# -*- coding: utf-8 -*-
"""Day3_Gradio_HF_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y71a-nh15bW3pkkA5dFn3v21yfms66uL

# Introduction
The purpose of this exercise is to get familiar with HuggingFace models, invoking them through Python code. Exposing these models for various tasks and using Gradio UI for easy access.
"""

import gradio as gr
from transformers import pipeline

# Load the pipeline with default model
sa_model = pipeline("sentiment-analysis")

def analyze_sentiment(text):
    if not text.strip():
        return "Dont be blank... enter any text in the input box!"

    result = sa_model(text)[0]
    return f"{result['label']} (confidence: {result['score']:.4f})"


demo_page = gr.Interface(
    fn=analyze_sentiment,
    inputs=gr.Textbox(lines=2,
                      label="Enter Text ",
                      placeholder="Type something..."
    ),
    outputs=gr.Textbox(label="Sentiment"),
    title="Sentiment Analyzer",
    description="My first LLM lab!"

)

demo_page.launch()

"""
# Conclusion
Still trying to get a grasp of the Collab, Gradio and HF. Seems Gradio and transformers need not be installed to get it run. Having hard time with syntax lookups after getting pampered in VS code. Also have not setup HF token, got a message at first run, subsequently it does not complain!
Overall great experience!"""
